### ISSUE TITLE
[PE-D][Tester D] Allows for adding duplicate groceries

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-T12-2/tp#121]
![Screenshot 2024-04-05 171934.png](https://raw.githubusercontent.com/pqienso/ped/main/files/7bf7e497-63b2-465c-8e6b-7e13ef7bcb2f.png)
Multiple groceries of the same name can be added to the list.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: pqienso/ped#7

**Comment by wallywallywally** [comment]
Prevent duplicate groceries from being added by throwing an exception.
