### ISSUE TITLE
[PE-D][Tester E] Fatal bug for "del" command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-T12-2/tp#123]
![image.png](https://raw.githubusercontent.com/runxinghuan/ped/main/files/c3bf53ff-bbb7-417d-8b60-d8fa620ff5e9.png)
ksjv is my first grocery in the list.
When I "del ksjv", there is an exception, and the app crashes.

![image.png](https://raw.githubusercontent.com/runxinghuan/ped/main/files/33cae453-00c6-4625-8fbb-f322b20dd3eb.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: runxinghuan/ped#9

**Comment by wallywallywally** [comment]
Issue related to deletion from storage location. Check if grocery to be deleted even has a storage location associated.
