### ISSUE TITLE
[PE-D][Tester E] Name of the profile is set to null in the beginning

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113-T12-2/tp#132]
![image.png](https://raw.githubusercontent.com/runxinghuan/ped/main/files/de327b37-c017-4530-9a54-c480987815c9.png)
When I start the app, the app has already asked my name, but my name is still null when I view the profile.

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: runxinghuan/ped#12

**Comment by wallywallywally** [comment]
Fixed in PR #153. `Parser` initialises `UserInfo` only once, so username always stays at `null`.
