### ISSUE TITLE
[PE-D][Tester A] Recipe.view bug

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-T12-2/tp#139]
# Description
View feature does not work on certain recipes, possibly with invalid inputs?

# Reproduction
(see examples below)

# Example
## Actual 
![image.png](https://raw.githubusercontent.com/NGXZS/ped/main/files/c370da1f-ebdb-4aa8-9ade-cd9bbcc3943d.png)

## Expected

![image.png](https://raw.githubusercontent.com/NGXZS/ped/main/files/8a73ad15-2d32-4c06-a503-561fa9a658be.png)

jiayouss

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: NGXZS/ped#7

**Comment by SharlynLui** [comment]
The recipe does not exist as the wrong input is passed in. Expected: name of recipe. Given: command word + name of recipe
