### ISSUE TITLE
[PE-D][Tester A] Minor Formatting alignment errors when printing recipe.view()

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-T12-2/tp#142]
# Description
Minor Formatting alignment errors when printing `recipe.view()`

# Example

![image.png](https://raw.githubusercontent.com/NGXZS/ped/main/files/1cee73f3-3f00-41ee-b13d-55ab3475ca6b.png)

jiayous

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: NGXZS/ped#8

**Comment by SharlynLui** [comment]
Fixed
