### ISSUE TITLE
use feature in Grocery

### ISSUE THREAD

**Issue by SharlynLui** [AY2324S2-CS2113-T12-2/tp#158]
![image](https://github.com/AY2324S2-CS2113-T12-2/tp/assets/110774281/83baf399-1f7c-40f8-8bce-f36f16b9d68d)
able to use more than amount of grocery

**Comment by wallywallywally** [comment]
This was intended, as it meant that users used up all their grocery. Should we change it if we think it's misleading?

**Comment by wallywallywally** [comment]
Will leave as is, but highlight this case more clearly in the User Guide.
